### ISSUE TITLE
pack source code as a .crx file

### ISSUE THREAD

**Issue by kernel1994** [gaozhengjie/jd_auto_jump#1]
Good idea!

But this seems a Chrome extension, so could you please pack source code as a `.crx` file?
Additional suggest, add a description about how to use this in `README` for who are unfamiliar with it.

Thanks!

**Comment by gaozhengjie** [comment]
> Good idea!
> 
> But this seems a Chrome extension, so could you please pack source code as a `.crx` file?
> Additional suggest, add a description about how to use this in `README` for who are unfamiliar with it.
> 
> Thanks!

**Comment by gaozhengjie** [comment]
> Good idea!
> 
> But this seems a Chrome extension, so could you please pack source code as a `.crx` file?
> Additional suggest, add a description about how to use this in `README` for who are unfamiliar with it.
> 
> Thanks!

Thanks for your suggestion, I have fixed it.
